### ISSUE TITLE
Does not compile on my 10.15.7 OsX machine

### ISSUE THREAD

**Issue by electronicbites** [synrc/fs#61]
No matter what I try, I get 

```mix deps.compile fs
==> fs (compile)
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)

ERROR: sh(clang c_src/mac/cli.o c_src/mac/compat.o c_src/mac/main.o -framework CoreFoundation -framework CoreServices  -L"/usr/local/Cellar/erlang/23.0.4/lib/erlang/lib/erl_interface-4.0/lib" -lerl_interface -lei -o priv/mac_listener)
failed with return code 1 and the following output:
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have the newest version of erlang installed: 

```erl
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.1.1  (abort with ^G)
```

I installed the gem `rb-fsevent` and it seems to work for me. I guess it has something to do with the new OTP 23 interface.

**Comment by 5HT** [comment]
Seems we have to remove `erl_interface` and `ei` from the following line in MAD:

https://github.com/synrc/mad/blob/master/src/compile/mad_port.erl#L126

The reason is that on 23 Erlang we no longer have both `erl_interface` and `ei` libraries. So removing them from mad should resolve mad builds on 23.

**Comment by 5HT** [comment]
Fixed in new MAD. You now may retry.

**Comment by electronicbites** [comment]
that worked, thanks!!!
